# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities
from selenium.webdriver.edge.service import Service

# 把下面的路径改成你 chromedriver.exe 的实际路径
webdriver_driver_path = r"C:\Users\HKY\AppData\Local\Programs\Python\Python39\msedgedriver.exe"
service = Service(webdriver_driver_path)

class TestDefaultSuite():
  def setup_method(self, method):
    self.driver = webdriver.Edge(service=service)
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def wait_for_window(self, timeout = 2):
    time.sleep(round(timeout / 1000))
    wh_now = self.driver.window_handles
    wh_then = self.vars["window_handles"]
    if len(wh_now) > len(wh_then):
      return set(wh_now).difference(set(wh_then)).pop()
  
  def test_testLearnReactLink(self):
    # Test name: Test_LearnReact_Link
    # Step # | name | target | value
    # 1 | open | / | 
    self.driver.get("http://localhost:3000/")
    # 2 | setWindowSize | 1017x852 | 
    self.driver.set_window_size(1017, 852)
    # 3 | click | linkText=我的第一个测试项目 | 
    self.vars["window_handles"] = self.driver.window_handles
    # 4 | selectWindow | handle=${win6894} | 
    self.driver.find_element(By.LINK_TEXT, "我的第一个测试项目").click()
    # 5 | click | css=.lg\3Amt-24 | 
    self.vars["win6894"] = self.wait_for_window(2000)
    self.driver.switch_to.window(self.vars["win6894"])
    self.driver.find_element(By.CSS_SELECTOR, ".lg\\3Amt-24").click()
  
  def test_testClickLogo(self):
    # Test name: Test_ClickLogo
    # Step # | name | target | value
    # 1 | open | / | 
    self.driver.get("http://localhost:3000/")
    # 2 | setWindowSize | 1018x852 | 
    self.driver.set_window_size(1018, 852)
    # 3 | click | css=.App-header | 
    self.driver.find_element(By.CSS_SELECTOR, ".App-header").click()
  
  def test_testCounterButton(self):
    # Test name: Test_CounterButton
    # Step # | name | target | value
    # 1 | open | / | 
    self.driver.get("http://localhost:3000/")
    # 2 | setWindowSize | 1017x852 | 
    self.driver.set_window_size(1017, 852)
    # 3 | click | css=button | 
    self.driver.find_element(By.CSS_SELECTOR, "button").click()
    # 4 | click | css=button | 
    self.driver.find_element(By.CSS_SELECTOR, "button").click()
    # 5 | click | css=button | 
    self.driver.find_element(By.CSS_SELECTOR, "button").click()
    # 6 | assertText | css=button | 点我 +1
    assert self.driver.find_element(By.CSS_SELECTOR, "button").text == "点我 +1"
  
  def test_testPageTitle(self):
    # Test name: Test_PageTitle
    # Step # | name | target | value
    # 1 | open | / | 
    self.driver.get("http://localhost:3000/")
    # 2 | setWindowSize | 1018x852 | 
    self.driver.set_window_size(1018, 852)
    # 3 | click | linkText=我的第一个测试项目 | 
    self.vars["window_handles"] = self.driver.window_handles
    # 4 | selectWindow | handle=${win7617} | 
    self.driver.find_element(By.LINK_TEXT, "我的第一个测试项目").click()
    # 5 | assertText | css=.uwu-hidden:nth-child(3) | React
    self.vars["win7617"] = self.wait_for_window(2000)
    self.driver.switch_to.window(self.vars["win7617"])
    assert self.driver.find_element(By.CSS_SELECTOR, ".uwu-hidden:nth-child(3)").text == "React"
  
